import React from 'react';
import ToolPage from '../components/ToolPage';

export default function MeeshoCourierInvoiceCrop() {
  return (
    <ToolPage
      title="Meesho Courier Label Crop Tool (With Invoice)"
      subtitle="Crop courier-generated Meesho labels and keep the invoice separate"
      marketplace="meesho_courier_invoice"
      metaTitle="Meesho Courier Label Cropper With Invoice - Free PDF Tool"
      metaDescription="Crop courier-generated Meesho labels while keeping invoice pages separate for clean seller dispatch printing."
      canonicalPath="/meesho-courier-label-cropper-with-invoice"
      description="Handles courier-generated labels while keeping the tax invoice as its own cropped page for compliance and customer documentation."
      features={[
        { title: 'Courier Format Support', desc: 'Handles the special format generated by couriers on Meesho.', icon: '🚚' },
        { title: 'Preserves Invoice', desc: 'Keeps the tax invoice alongside the shipping label.', icon: '📄' }
      ]}
      seoContent={`
        <h2>Meesho courier label cropper with invoice</h2>
        <p>Use this page when the courier-generated Meesho PDF includes both label and invoice content. The cropper keeps the invoice as a separate cropped page so the final file is easier to print and pack.</p>
      `}
    />
  );
}
