import React from 'react';
import ToolPage from '../components/ToolPage';

export default function MeeshoCourierCrop() {
  return (
    <ToolPage
      title="Meesho Courier Label Crop Tool (No Invoice)"
      subtitle="Crop courier-generated Meesho labels (label only, no invoice)"
      marketplace="meesho_courier"
      metaTitle="Meesho Courier Label Cropper - No Invoice PDF Tool"
      metaDescription="Crop courier-generated Meesho label PDFs and output label-only pages for 4x6 thermal or A4 printing."
      canonicalPath="/meesho-courier-label-cropper"
      description="Specifically designed for Meesho's courier-generated PDF format. This tool extracts only the shipping label and discards the invoice section."
      features={[
        { title: 'Courier Format Support', desc: 'Handles the special format generated by couriers on Meesho.', icon: '🚚' },
        { title: 'Label Only Extraction', desc: 'Outputs just the shipping label to save paper.', icon: '✂️' }
      ]}
      seoContent={`
        <h2>Meesho courier label cropper</h2>
        <p>This page is for Meesho courier-generated label PDFs where the seller wants a label-only output. It keeps the workflow simple for packing stations using thermal printers or A4 sheets.</p>
      `}
    />
  );
}
